name: github ci
on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  
jobs:
  ci:
    name: Deploy to LW
    runs-on: ubuntu-20.04
  
    steps:
    - name: Download files from the current repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 18.x
        
    - name: Install dependencies
      run: |
        npm i

    - name: production build
      run: |
        npm run build

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@0.0.1
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "build"
        remoteDir: "public_html"
